{"uuid": "b2ee13bb-c42e-49f0-9cd9-87ef006d0724", "children": ["5e7b6e5f-aa09-4b28-987f-a66422180b7e"], "befores": [{"name": "base_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=136.0.7103.93)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7F7E75335+78597]\n\tGetHandleVerifier [0x00007FF7F7E75390+78688]\n\t(No symbol) [0x00007FF7F7C291AA]\n\t(No symbol) [0x00007FF7F7C01B63]\n\t(No symbol) [0x00007FF7F7CAEB6E]\n\t(No symbol) [0x00007FF7F7CCEBB2]\n\t(No symbol) [0x00007FF7F7CA6EC3]\n\t(No symbol) [0x00007FF7F7C703F8]\n\t(No symbol) [0x00007FF7F7C71163]\n\tGetHandleVerifier [0x00007FF7F811EEED+2870973]\n\tGetHandleVerifier [0x00007FF7F8119698+2848360]\n\tGetHandleVerifier [0x00007FF7F8136973+2967875]\n\tGetHandleVerifier [0x00007FF7F7E9017A+188746]\n\tGetHandleVerifier [0x00007FF7F7E9845F+222255]\n\tGetHandleVerifier [0x00007FF7F7E7D2B4+111236]\n\tGetHandleVerifier [0x00007FF7F7E7D462+111666]\n\tGetHandleVerifier [0x00007FF7F7E63589+5465]\n\tBaseThreadInitThunk [0x00007FFAFEB2E8D7+23]\n\tRtlUserThreadStart [0x00007FFAFFD7C5DC+44]\n\n", "trace": "  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\tests\\conftest.py\", line 75, in base_fixture\n    base, sidebar = base_test_with_login(domain, role)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\tests\\base_test.py\", line 10, in base_test_with_login\n    login.authorization(role)\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\pages\\login_page.py\", line 56, in authorization\n    self.get_current_url()\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\base\\base_class.py\", line 118, in get_current_url\n    get_url = self.driver.current_url\n              ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 437, in current_url\n    return self.execute(Command.GET_CURRENT_URL)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\l2new\\PycharmProjects\\Vezubr_Autotests\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Start test", "status": "passed", "start": 1747382449613, "stop": 1747382449614}], "start": 1747382447935, "stop": 1747382453005}], "start": 1747382447935, "stop": 1747382454135}